name: Sync Bookshelf to This Repo

on:
  schedule:
    - cron: "0 0 * * *" # 北京时间每天早上8点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write # 只需要写Issue的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run sync
        run: npm run sync
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          WEREAD_PAT: ${{ secrets.WEREAD_PAT }}
          # 【关键】GITHUB_REPOSITORY 会由Actions自动提供
          GITHUB_REPOSITORY: ${{ github.repository }}

