name: Sync Issues to Blog Repo

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Prepare issue body file
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "原始仓库: [${{ github.repository }}#${{ github.event.issue.number }}](${{ github.event.issue.html_url }})" > issue-body.md
          echo "" >> issue-body.md
          echo "$ISSUE_BODY" >> issue-body.md

      - name: Find existing issue in target repo
        id: find
        uses: peter-evans/find-comment@v3
        with:
          # 关键：确认使用了正确的 TOKEN
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: granthuang999/granthuang999.github.io
          comment-author: github-actions[bot]
          body-includes: "${{ github.repository }}#${{ github.event.issue.number }}"

      - name: Update issue if exists
        if: steps.find.outputs.comment-id != ''
        run: |
          gh issue edit ${{ steps.find.outputs.issue-number }} \
            --title "${{ github.event.issue.title }}" \
            --body-file ./issue-body.md
        env:
          # 关键：gh 命令也需要使用正确的 TOKEN
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
          GH_REPO: granthuang999/granthuang999.github.io

      - name: Create issue if not exists
        if: steps.find.outputs.comment-id == ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          # 关键：创建 issue 也需要使用正确的 TOKEN
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: granthuang999/granthuang999.github.io
          title: ${{ github.event.issue.title }}
          content-filepath: ./issue-body.md
          labels: synced-from-weread
