name: Sync Issues to Blog Repo

on:
  # 允许手动触发
  workflow_dispatch:
  # 当源仓库的 issue 被创建或编辑时触发
  issues:
    types: [opened, edited]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出当前仓库代码
      - name: Checkout source repo
        uses: actions/checkout@v4

      # 2. 准备要同步到目标仓库的 issue 内容文件 (已修正)
      - name: Prepare issue body file
        # 将 issue body 传入环境变量，以避免特殊字符（如 |）导致的 shell 语法错误
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "原始仓库: [${{ github.repository }}#${{ github.event.issue.number }}](${{ github.event.issue.html_url }})" > issue-body.md
          echo "" >> issue-body.md
          # 从环境变量中安全地打印 issue body
          echo "$ISSUE_BODY" >> issue-body.md

      # 3. 在目标仓库中查找是否已存在同步过的 issue
      - name: Find existing issue in target repo
        id: find
        uses: peter-evans/find-comment@v3
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: granthuang999/granthuang999.github.io
          comment-author: github-actions[bot]
          body-includes: "${{ github.repository }}#${{ github.event.issue.number }}"

      # 4. 如果找到了对应的 issue，就更新它
      - name: Update issue if exists
        if: steps.find.outputs.comment-id != ''
        run: |
          gh issue edit ${{ steps.find.outputs.issue-number }} \
            --title "${{ github.event.issue.title }}" \
            --body-file ./issue-body.md
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
          GH_REPO: granthuang999/granthuang999.github.io

      # 5. 如果没有找到，就新建一个 issue
      - name: Create issue if not exists
        if: steps.find.outputs.comment-id == ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: granthuang999/granthuang999.github.io
          title: ${{ github.event.issue.title }}
          content-filepath: ./issue-body.md
          labels: synced-from-weread
