name: WeRead Bookshelf Sync

on:
  schedule:
    # 北京时间每天早上8点运行
    - cron: "0 0 * * *"
  # 允许从Actions标签手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      # 必须有写入权限才能提交回仓库
      contents: write
      # 必须有issues写入权限
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run sync
        run: npm run sync
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          WEREAD_PAT: ${{ secrets.WEREAD_PAT }}
          # 【关键修正】: GITHUB_REPO_OWNER 仍然是当前仓库的所有者
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          # 【关键修正】: GITHUB_REPO_NAME 现在从一个新的Secret读取，如果未设置，则默认为当前仓库名
          GITHUB_REPO_NAME: ${{ secrets.TARGET_REPO_NAME || github.event.repository.name }}

