name: WeRead to GitHub Issues Sync

on:
  schedule:
    # Runs at 00:00 UTC every day, which is 8:00 AM Beijing Time
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Important: Give the workflow permission to write to the repo (i.e., create/update issues)

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a stable version of Node.js
          cache: "npm"

      - name: Install dependencies
        run: npm ci # 'ci' is faster and more reliable for automated environments

      - name: Run the sync script
        run: npm run sync # This executes "ts-node src/index.ts --all"
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          GITHUB_TOKEN: ${{ secrets.WEREAD_PAT }} # Use a custom name for the Personal Access Token
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}

